name: Deploy to EC2 instance node js

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Debug secrets (safe check)
      - name: Debug Secrets
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "User: ${{ secrets.EC2_USER }}"
          echo "SSH Key length: $(echo "${{ secrets.EC2_SSH_KEY }}" | wc -c)"

      # 3. Copy project files to EC2
      - name: Upload app to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./**"
          target: "~/NODEAPP"

      # 4. Connect via SSH and restart the app
      - name: Restart Node App on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/NODEAPP
            npm install --production
            # kill old app (if running)
            pkill -f "node server.js" || true
            # start app in background
            nohup node server.js > app.log 2>&1 &
